0:
  mover: 
    class: Cartesian.Primitiv
    settings:
      port: COM7
      limits: [[-470,0,0], [0,0,0]]
      safe_height: 0
  liquid: 
    class: Liquid.SyringeAssembly
    settings:
      port: COM8
      capacities: [3000,3000,3000,3000,3000]
      channels: [3,4,5,6,7]
      offsets:
        - [-100,0,0]
        - [-75,0,0]
        - [-50,0,0]
        - [-25,0,0]
        - [0,0,0]
  maker: 
    class: ThinFilm.SpinnerAssembly
    settings:
      ports: &SpinnerPorts
      - COM16
      - COM15
      - COM14
      - COM13
      channels: &SpinnerChannels
      - 0
      - 1
      - 2
      - 3
      positions:
      - [-325,0,0]
      - [-250,0,0]
      - [-175,0,0]
      - [-100,0,0]
  labelled_positions:
    fill: [-370,0,0]
    rest: [-370,0,0]

1:
  mover: 
    class: Jointed.Dobot.M1Pro
    settings:
      ip_address: '192.168.2.21'
      home_coordinates: {'tuple': [300,0,200]}
      home_orientation: {'tuple': [0,0,0]}
      orientate_matrix: {'array': [[0,1,0],[-1,0,0],[0,0,1]]}
      translate_vector: {'array': [-281.9,335.1,198.7]}
      scale: 1
      implement_offset: {'tuple': [0,0,-250]}
  liquid: 
    class: Liquid.Sartorius.Sartorius
    settings:
      port: COM17
      channel: 1
      offset: [0,0,0]
  maker: 
    class: ThinFilm.SpinnerAssembly
    settings:
      ports: *SpinnerPorts
      channels: *SpinnerChannels
      positions:
      - [-258,-275,90]
      - [-257,-200,90]
      - [-255,-124,90]
      - [-254,-49,90]
  labelled_positions:
    fill: [-100,0,0]
    tips: [0,0,0]
    bins: [0,0,0]