services:
  controllable:
    image: controllably
    container_name: controllably-server
    build:
      context: .
      dockerfile: ./dev/Dockerfile
      target: runner
    ports:
      - 8000:8000
