0:
  mover: 
    class: Cartesian.Primitiv
    settings:
      port: COM8
      xyz_bounds: [[-410,-290,-120], [0,0,0]]
      Z_safe: -80
  measurer: &Keithley
    class: Electrical.Keithley.Keithley
    settings:
      ip_address: '192.168.1.125'
  height: &height
    settings:
      names: ['up','down']
      z_heights: [-94,-104]
      overwrite: False

1:
  mover:
    class: Cartesian.Ender
    settings:
      port: COM8
      xyz_bounds: [[0,0,0], [240,235,210]]
      Z_safe: 30
  measurer: *Keithley
  height: *height
