controllable:
  Compound:
    LiquidMover:
      liquidmover_utils:
        TIP_APPROACH_HEIGHT: 20 # height above tip rack before approaching slowly [mm]
  Measure:
    Physical:
      balance_utils:
        CALIBRATION_FACTOR: 6.862879436681862 # factor by which to divide output reading by to get mass in mg
  Move:
    Cartesian:
      cartesian_utils:
        CNC_SPEED: 250 # [mm/s]
  Transfer:
    Liquid:
      Sartorius:
        sartorius_utils:
          DEFAULT_AIRGAP: 10 # number of plunger steps for air gap
          DEFAULT_PULLBACK: 5 # number of plunger steps for pullback
          TIME_RESOLUTION: 1.03 # minimum drive response time [s]
          TIP_THRESHOLD: 276 # capacitance value above which tip is attached
      syringe_utils:
        CALIBRATION_ASPIRATE: 27 # 
        CALIBRATION_DISPENSE: 23.5 #
        DEFAULT_SPEED: 3000 # rotation speed of peristaltic pump [rpm]
        PULLBACK_TIME: 2 # amount of time to pullback [s]
