name: Publish to PyPI

on:
  push:
    tags:
    # Trigger PyPI upload on version tags (e.g., v0.1.0)
    - 'v[0-9]+.[0-9]+.[0-9]+'
    - 'v[0-9]+.[0-9]+.[0-9]+a[0-9]+'
    - 'v[0-9]+.[0-9]+.[0-9]+b[0-9]+'
    - 'v[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest # Run the job on an Ubuntu virtual machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Action to checkout your repository code

      - name: Set up Python
        uses: actions/setup-python@v2 # Action to set up Python environment
        with:
          python-version: '3.12' # Use a recent Python version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Build sdist and wheel
        run: python -m build --sdist --wheel .

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*
